#!/usr/bin/env bash
set -euo pipefail

# Generated by build.sh; each release embeds its own artifact checksums.
version='0.4.41-zh-tw.5'
base_url='https://github.com/hyc5566/multica/releases/download/zh-tw-v0.4.41-zh-tw.5'
[[ ${1:-} == "" || ${1:-} == --login || ${1:-} == --service ]] || { echo 'Usage: install.sh [--login|--service]' >&2; exit 2; }
[[ $# -le 1 ]] || { echo 'Usage: install.sh [--login|--service]' >&2; exit 2; }
# Refuse to redirect or overwrite a pre-existing account configuration.
if [[ -n ${MULTICA_PROFILE:-} || -e "$HOME/.multica/config.json" || -L "$HOME/.multica/config.json" ]]; then
  echo 'Existing configuration/profile found. Keep it and use the documented upgrade procedure.' >&2
  exit 2
fi
case "$(uname -s)-$(uname -m)" in
  Linux-x86_64) platform=linux-amd64; checksum='b95647e54c8ca99d84ce7156a7e4b2dc4125b9256a1697eb08396ae1fcb173f3' ;;
  Linux-aarch64|Linux-arm64) platform=linux-arm64; checksum='4ccff095ab0d945765d573ec539bcfc6dd3d2c0ed0a4d4a47175f505281478ec' ;;
  Darwin-x86_64) platform=darwin-amd64; checksum='c95142f5cacd8595526c1971b093ede05a2a13912f4116f6da0f182238114d2c' ;;
  Darwin-arm64) platform=darwin-arm64; checksum='783ee6eb42fd85e7657f4503aa15ff0a3cdc81eac85038639088d1f9fd4151e2' ;;
  *) echo 'Unsupported platform; use a matching release binary.' >&2; exit 2 ;;
esac

if [[ ${1:-} == --service ]]; then
  [[ $(uname -s) == Linux ]] || { echo '--service requires Linux systemd user services.' >&2; exit 2; }
  command -v systemctl >/dev/null
  systemctl --user show-environment >/dev/null
  [[ ! -e "$HOME/.config/systemd/user/multica.service" && ! -L "$HOME/.config/systemd/user/multica.service" ]] || {
    echo 'Existing multica.service found; refusing to replace it.' >&2; exit 2;
  }
fi
install_root=${MULTICA_ZH_TW_INSTALL_ROOT:-"$HOME/.local"}
case "$install_root" in
  /*) ;;
  *) echo 'Installation root must be absolute.' >&2; exit 2 ;;
esac
destination="$install_root/share/multica-zh-tw/$version"
wrapper="$install_root/bin/multica"
if [[ -e "$destination" || -L "$destination" || -e "$wrapper" || -L "$wrapper" ]]; then
  echo 'Existing installation found. Review the upgrade procedure before replacing it.' >&2
  exit 2
fi
for required in curl tar; do command -v "$required" >/dev/null; done
tmp=$(mktemp -d)
trap 'rm -rf -- "$tmp"' EXIT
curl --fail --silent --show-error --location --proto '=https' --proto-redir '=https' \
  "$base_url/multica-$platform.tar.gz" -o "$tmp/archive.tar.gz"
if command -v sha256sum >/dev/null; then
  actual=$(sha256sum "$tmp/archive.tar.gz")
else
  actual=$(shasum -a 256 "$tmp/archive.tar.gz")
fi
[[ ${actual%% *} == "$checksum" ]] || { echo 'Checksum mismatch.' >&2; exit 1; }
tar -xzf "$tmp/archive.tar.gz" -C "$tmp" multica LICENSE NOTICE s90-ca.crt
[[ -f "$tmp/multica" && ! -L "$tmp/multica" ]] || exit 1
mkdir -p "$install_root/bin" "$(dirname "$destination")"
# mkdir reserves the version directory without overwriting an existing install.
mkdir "$destination"
install -m 755 "$tmp/multica" "$destination/multica"
install -m 644 "$tmp/LICENSE" "$tmp/NOTICE" "$tmp/s90-ca.crt" "$destination/"
# Preserve public roots for provider tools inherited by the daemon.
public_ca=''
for candidate in /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/cert.pem; do
  if [[ -r "$candidate" ]]; then public_ca="$candidate"; break; fi
done
[[ -n "$public_ca" ]] || { echo 'System CA bundle not found; install the OS ca-certificates package first.' >&2; exit 1; }
cat "$public_ca" > "$destination/ca-bundle.crt"
printf '\n' >> "$destination/ca-bundle.crt"
cat "$destination/s90-ca.crt" >> "$destination/ca-bundle.crt"
# Bash %q quotes spaces and metacharacters in the user's installation path.
{
  printf '#!/usr/bin/env bash\n'
  printf 'export MULTICA_DAEMON_AUTO_UPDATE=false MULTICA_DAEMON_AUTO_RELOAD=false MULTICA_DAEMON_DYNAMIC_PORT=true\n'
  printf 'export SSL_CERT_FILE=%q\n' "$destination/ca-bundle.crt"
  printf 'export MULTICA_SERVER_URL=https://10.1.24.90:45671 MULTICA_APP_URL=https://10.1.24.90:45671\n'
  printf 'exec %q "$@"\n' "$destination/multica"
} > "$tmp/wrapper"
chmod 755 "$tmp/wrapper"
# A hard link creates the destination atomically and fails if already present.
install -m 755 "$tmp/wrapper" "$destination/launcher"
ln "$destination/launcher" "$wrapper"
# New installs keep task working directories separate from config and tokens.
"$wrapper" config set workspaces_root "$HOME/.multica/workspaces"
printf 'Installed %s.\n' "$version"
printf 'Command: %s\n' "$wrapper"

if [[ ${1:-} == --login || ${1:-} == --service ]]; then
  "$wrapper" login --token
  if [[ ${1:-} == --service ]]; then
    # Escape quoted systemd values, including specifiers and ExecStart dollars.
    unit_escape() { local value=$1; value=${value//\\/\\\\}; value=${value//\"/\\\"}; value=${value//%/%%}; printf '%s' "$value"; }
    unit_wrapper=$(unit_escape "$wrapper")
    unit_wrapper=${unit_wrapper//\$/\$\$}
    unit_path=$(unit_escape "$PATH")
    mkdir -p "$HOME/.config/systemd/user"
    cat > "$HOME/.config/systemd/user/multica.service" <<UNIT
[Unit]
Description=Multica user daemon
After=network-online.target

[Service]
Type=simple
ExecStart="$unit_wrapper" daemon start --foreground
Environment="PATH=$unit_path"
Restart=on-failure
RestartSec=5
TimeoutStopSec=90

[Install]
WantedBy=default.target
UNIT
    systemctl --user daemon-reload
    systemctl --user enable --now multica.service
    ready=false
    for ((attempt=0; attempt<45; attempt++)); do
      if "$wrapper" daemon status --output json | grep -Eq '\"status\"[[:space:]]*:[[:space:]]*\"running\"'; then ready=true; break; fi
      sleep 1
    done
    [[ $ready == true ]] || { echo 'Service started but registration readiness timed out. Check journalctl --user -u multica.service.' >&2; exit 1; }
    echo 'Service ready. Stop: systemctl --user stop multica.service'
    echo 'Restart: systemctl --user restart multica.service'
    echo 'Starts with your user session; boot without login requires administrator-managed lingering.'
  else
    "$wrapper" daemon start
  fi
else
  printf 'Next: %q login --token\nThen: %q daemon start\n' "$wrapper" "$wrapper"
fi
