#!/usr/bin/env bash
set -euo pipefail

# Generated by build.sh; each release embeds its own artifact checksums.
version='0.4.43-zh-tw.1'
base_url='https://10.1.24.90:45671/downloads/0.4.43-zh-tw.1'
ca_url="$base_url/s90-ca.crt"
ca_checksum='51447dbdb7d2f6817ada4b45565aefa86e813e726ee34977112ffd3a946a62ee'
[[ ${1:-} == "" || ${1:-} == --login || ${1:-} == --service ]] || { echo 'Usage: install.sh [--login|--service]' >&2; exit 2; }
[[ $# -le 1 ]] || { echo 'Usage: install.sh [--login|--service]' >&2; exit 2; }
# Refuse to redirect or overwrite a pre-existing account configuration.
if [[ -n ${MULTICA_PROFILE:-} || -e "$HOME/.multica/config.json" || -L "$HOME/.multica/config.json" ]]; then
  echo 'Existing configuration/profile found. Keep it and use the documented upgrade procedure.' >&2
  exit 2
fi
case "$(uname -s)-$(uname -m)" in
  Linux-x86_64) platform=linux-amd64; checksum='145241e6ab9d4e0254864c82ca4cb9c6ed887d5dfbbcbc1feafd3cfae030559c' ;;
  Linux-aarch64|Linux-arm64) platform=linux-arm64; checksum='099b1526e2afc90c0fdb198e439e6ff4e30e2d592aa91f5379240e10ccb2156a' ;;
  Darwin-x86_64) platform=darwin-amd64; checksum='40542282827a516e9659850a63aa6154380689fabad7ba2c35847aed24ef483d' ;;
  Darwin-arm64) platform=darwin-arm64; checksum='55caa54430a8845c4957f2deb5cf814f53dec9b79836adefa70b1241549d33b2' ;;
  *) echo 'Unsupported platform; use a matching release binary.' >&2; exit 2 ;;
esac

if [[ ${1:-} == --service ]]; then
  [[ $(uname -s) == Linux ]] || { echo '--service requires Linux systemd user services.' >&2; exit 2; }
  command -v systemctl >/dev/null
  systemctl --user show-environment >/dev/null
  [[ ! -e "$HOME/.config/systemd/user/multica.service" && ! -L "$HOME/.config/systemd/user/multica.service" ]] || {
    echo 'Existing multica.service found; refusing to replace it.' >&2; exit 2;
  }
fi
install_root=${MULTICA_ZH_TW_INSTALL_ROOT:-"$HOME/.local"}
case "$install_root" in
  /*) ;;
  *) echo 'Installation root must be absolute.' >&2; exit 2 ;;
esac
destination="$install_root/share/multica-zh-tw/$version"
wrapper="$install_root/bin/multica"
if [[ -e "$destination" || -L "$destination" || -e "$wrapper" || -L "$wrapper" ]]; then
  echo 'Existing installation found. Review the upgrade procedure before replacing it.' >&2
  exit 2
fi
for required in curl tar grep; do command -v "$required" >/dev/null; done
tmp=$(mktemp -d)
trap 'rm -rf -- "$tmp"' EXIT
# Establish download trust before contacting the artifact server. A private-only inherited
# CA bundle must not hide the OS public roots. Keep explicitly provided roots.
public_ca=''
for candidate in /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/cert.pem; do
  if [[ -f "$candidate" && -r "$candidate" && -s "$candidate" ]]; then public_ca="$candidate"; break; fi
done
[[ -n "$public_ca" ]] || { echo 'System CA bundle not found; install the OS ca-certificates package first.' >&2; exit 1; }
if [[ -n ${MULTICA_INSTALL_CA_FILE:-} && ( ! -f "$MULTICA_INSTALL_CA_FILE" || ! -r "$MULTICA_INSTALL_CA_FILE" || ! -s "$MULTICA_INSTALL_CA_FILE" ) ]]; then
  echo 'MULTICA_INSTALL_CA_FILE must name a readable, non-empty public CA certificate file.' >&2
  exit 1
fi
if grep -Eq -- '-----BEGIN .*PRIVATE KEY-----' "$public_ca"; then
  echo 'CA bundle contains a private key; use public CA certificates only.' >&2; exit 1
fi
cat "$public_ca" > "$tmp/download-ca.crt"
for candidate in "${CURL_CA_BUNDLE:-}" "${SSL_CERT_FILE:-}" "${MULTICA_INSTALL_CA_FILE:-}"; do
  if [[ -n "$candidate" && "$candidate" != "$public_ca" && -f "$candidate" && -r "$candidate" && -s "$candidate" ]]; then
    if grep -Eq -- '-----BEGIN .*PRIVATE KEY-----' "$candidate"; then
      echo 'CA bundle contains a private key; use public CA certificates only.' >&2; exit 1
    fi
    printf '\n' >> "$tmp/download-ca.crt"
    cat "$candidate" >> "$tmp/download-ca.crt"
  fi
done
# Bootstrap only the public CA bytes without relying on an already-trusted LAN
# certificate. The checksum in this trusted installer authenticates them BEFORE
# they become a trust root. No redirects, credentials, or artifact requests here.
sha256_file() {
  if command -v sha256sum >/dev/null; then sha256sum "$1"; else shasum -a 256 "$1"; fi
}
curl -q --insecure --proxy-cacert "$tmp/download-ca.crt" \
  --fail --silent --show-error --proto '=https' --max-filesize 1048576 \
  --connect-timeout 10 --max-time 60 "$ca_url" -o "$tmp/bootstrap-ca.crt"
actual=$(sha256_file "$tmp/bootstrap-ca.crt")
[[ ${actual%% *} == "$ca_checksum" ]] || { echo 'CA checksum mismatch; no certificate was trusted or installation written.' >&2; exit 1; }
printf '\n' >> "$tmp/download-ca.crt"
cat "$tmp/bootstrap-ca.crt" >> "$tmp/download-ca.crt"
# -q must be first: a user curlrc must not inject insecure or alternate downloads.
# HTTPS proxies have their own TLS verification, using the same approved roots.
if curl -q --cacert "$tmp/download-ca.crt" --proxy-cacert "$tmp/download-ca.crt" \
  --fail --silent --show-error --location --proto '=https' --proto-redir '=https' \
  "$base_url/multica-$platform.tar.gz" -o "$tmp/archive.tar.gz"; then
  :
else
  status=$?
  if [[ $status == 60 || $status == 77 ]]; then
    echo 'TLS verification failed while downloading the CLI; no installation was written.' >&2
    echo 'For a company TLS proxy, supply its administrator-verified public CA via MULTICA_INSTALL_CA_FILE and retry. TLS verification remains enabled.' >&2
  fi
  exit "$status"
fi
actual=$(sha256_file "$tmp/archive.tar.gz")
[[ ${actual%% *} == "$checksum" ]] || { echo 'Checksum mismatch.' >&2; exit 1; }
tar -xzf "$tmp/archive.tar.gz" -C "$tmp" multica LICENSE NOTICE s90-ca.crt
[[ -f "$tmp/multica" && ! -L "$tmp/multica" ]] || exit 1
mkdir -p "$install_root/bin" "$(dirname "$destination")"
# mkdir reserves the version directory without overwriting an existing install.
mkdir "$destination"
install -m 755 "$tmp/multica" "$destination/multica"
install -m 644 "$tmp/LICENSE" "$tmp/NOTICE" "$tmp/s90-ca.crt" "$destination/"
# Reuse the verified download trust and add the archive's checksum-pinned s90 CA.
cat "$tmp/download-ca.crt" > "$destination/ca-bundle.crt"
printf '\n' >> "$destination/ca-bundle.crt"
cat "$destination/s90-ca.crt" >> "$destination/ca-bundle.crt"
# Bash %q quotes spaces and metacharacters in the user's installation path.
{
  printf '#!/usr/bin/env bash\n'
  printf 'export MULTICA_DAEMON_AUTO_UPDATE=false MULTICA_DAEMON_AUTO_RELOAD=false MULTICA_DAEMON_DYNAMIC_PORT=true\n'
  printf 'export MULTICA_CA_CERT_FILE=%q\n' "$destination/ca-bundle.crt"
  printf 'export SSL_CERT_FILE=%q\n' "$destination/ca-bundle.crt"
  printf 'export CURL_CA_BUNDLE=%q\n' "$destination/ca-bundle.crt"
  printf 'export MULTICA_SERVER_URL=https://10.1.24.90:45671 MULTICA_APP_URL=https://10.1.24.90:45671\n'
  printf 'exec %q "$@"\n' "$destination/multica"
} > "$tmp/wrapper"
chmod 755 "$tmp/wrapper"
# A hard link creates the destination atomically and fails if already present.
install -m 755 "$tmp/wrapper" "$destination/launcher"
ln "$destination/launcher" "$wrapper"
# New installs keep task working directories separate from config and tokens.
"$wrapper" config set workspaces_root "$HOME/.multica/workspaces"
printf 'Installed %s.\n' "$version"
printf 'Command: %s\n' "$wrapper"

if [[ ${1:-} == --login || ${1:-} == --service ]]; then
  "$wrapper" login --token
  if [[ ${1:-} == --service ]]; then
    # Escape quoted systemd values, including specifiers and ExecStart dollars.
    unit_escape() { local value=$1; value=${value//\\/\\\\}; value=${value//\"/\\\"}; value=${value//%/%%}; printf '%s' "$value"; }
    unit_wrapper=$(unit_escape "$wrapper")
    unit_wrapper=${unit_wrapper//\$/\$\$}
    unit_path=$(unit_escape "$PATH")
    mkdir -p "$HOME/.config/systemd/user"
    cat > "$HOME/.config/systemd/user/multica.service" <<UNIT
[Unit]
Description=Multica user daemon
After=network-online.target

[Service]
Type=simple
ExecStart="$unit_wrapper" daemon start --foreground
Environment="PATH=$unit_path"
Restart=on-failure
RestartSec=5
TimeoutStopSec=90

[Install]
WantedBy=default.target
UNIT
    systemctl --user daemon-reload
    systemctl --user enable --now multica.service
    ready=false
    for ((attempt=0; attempt<45; attempt++)); do
      if "$wrapper" daemon status --output json | grep -Eq '\"status\"[[:space:]]*:[[:space:]]*\"running\"'; then ready=true; break; fi
      sleep 1
    done
    [[ $ready == true ]] || { echo 'Service started but registration readiness timed out. Check journalctl --user -u multica.service.' >&2; exit 1; }
    echo 'Service ready. Stop: systemctl --user stop multica.service'
    echo 'Restart: systemctl --user restart multica.service'
    echo 'Starts with your user session; boot without login requires administrator-managed lingering.'
  else
    "$wrapper" daemon start
  fi
else
  printf 'Next: %q login --token\nThen: %q daemon start\n' "$wrapper" "$wrapper"
fi
